### ISSUE TITLE
LWG3545 std::pointer_traits should be SFINAE-friendly

### ISSUE THREAD

**Issue by jwakely** [cplusplus/papers#1038]
Issue: https://cplusplus.github.io/LWG/issue3545

During the LWG prioritization poll it was suggested that this should be seen by LEWG to answer some open questions.

**Comment by cor3ntin** [comment]
Mailing list discussions failed to gather a crowd. @jwakely kindly offered to write a paper with a more comprehensive fix matching his implementation, along the following lines
``` 
if pointer_traits<P>::element_type cannot be deduced, then pointer_traits<P> is an empty class.
So you could use the existence of pointer_traits<P>::element_type
(or pointer_traits<P>::pointer or pointer_traits<P>::difference_type) 
to check whether something is pointer-like
```

My assumption is that this fix would be applied as a fix to C++20, so it need not be seen in the context of the C++23 schedule, but I am sure implementers are eager for a resolution as this bugs is affecting users.

**Comment by billy-baker** [comment]
LEWG review 2022-02-22.

__POLL:__ LWG3579 "Complexity guarantees for resize() and append() functions across the library" should be closed as NAD. (A paper would be needed for changes.)

No objection to unanimous consent to close as NAD.

As shown in the poll, a paper would be needed in order to make changes. Such a paper would need to include a discussion on whether allocate_at_least (new for C++23) has an impact.

**Comment by billy-baker** [comment]
Reviewed in LEWG Telecon 2022-02-22.

__POLL:__ pointer_traits should be SFINAE friendly (LWG3545).

No objections to unanimous consent.

**Comment by jwakely** [comment]
Thanks, I'll get the paper finished then.

**Comment by frederick-vs-ja** [comment]
LWG3545 has been voted into WP, so should we close this issue?

**Comment by jwakely** [comment]
We should, thanks.
