### ISSUE TITLE
LWG3565: Handling of encodings in localized formatting of chrono types is underspecified

### ISSUE THREAD

**Issue by jwakely** [cplusplus/papers#1053]
SG16 needs to clarify the intended design for https://cplusplus.github.io/LWG/issue3565

**Comment by tahonermann** [comment]
SG16 will do so at its 2021-06-23 telecon.

**Comment by tahonermann** [comment]
SG16 did not get to this at its 2021-06-23 telecon; it is now the first item on the agenda for our 2021-07-14 telecon.

**Comment by tahonermann** [comment]
SG16 did not get to this at its 2021-07-14 telecon (the agenda was changed to allow progress on other issues).  This is now the first item on the agenda for our 2021-07-28 telecon (and it will remain there).

**Comment by cor3ntin** [comment]
This is resolved by #1093

**Comment by tahonermann** [comment]
For historical reference, SG16 discussed this issue during its [July 28th, 2021 telecon](https://github.com/sg16-unicode/sg16-meetings#july-28th-2021). The following polls were taken.

**Poll 1: Require implementations to make std::chrono substitutions with std::format as if transcoded to UTF-8 when the literal ecoding E associated with the format string is UTF-8, for an implementation-defined set of locales.**
- Attendance: 9
- | SF |  F |  N |  A | SA
  | --: | --: | --: | --: | --:
  | 1 | 6 | 2 | 0 | 0
- Consensus in favor.

**Poll 2: Permit such substitutions when the encoding E is any Unicode encoding form.**
- Attendance: 9
- | SF |  F |  N |  A | SA
  | --: | --: | --: | --: | --:
  | 0 | 7 | 2 | 0 | 0
- Consensus in favor.

**Poll 3: Prohibit such substitutions otherwise.**
- Attendance: 9
- | SF |  F |  N |  A | SA
  | --: | --: | --: | --: | --:
  | 1 | 3 | 3 | 1 | 1
- No consensus.
- SA: This is an over constraint; should permit implementations to do best effort work.

Removing the SG16 label. This issue is now tracked by [P2419](https://wg21.link/p2419) (#1093).
