### ISSUE TITLE
LWG3576: Clarifying fill character in std::format

### ISSUE THREAD

**Issue by jwakely** [cplusplus/papers#1090]
SG16 needs to clarify the intended design for https://cplusplus.github.io/LWG/issue3576

"The fill character should at least be a codepoint, definitively - Whether we allow it to be a grapheme cluster is an interesting question and probably requires *some* discussion.  
We definitely do not want to use the term character in such an ambiguous context!"

"The wording is definitely wrong anyway, considering that it only changes a non-normative note."

**Comment by tahonermann** [comment]
My last comment noted two issues for SG16 to follow up on. The first is a non-issue that does not require follow up; escape sequences cannot be used to evade unintended delimiter matching since the format string is a cooked string (escape sequences are already processed). The second issue is now tracked by https://github.com/cplusplus/papers/issues/1150.

I'm still retaining the SG16 label for now as the proposed resolution for this issue needs some tweaking; recent discussion indicates that we may have to specify "multibyte character" rather than "code point" in the wording in order to accommodate shift-state encodings that don't have a clear concept of "code point".

**Comment by tahonermann** [comment]
SG16 discussed (a draft of) [P2572R0](https://wg21.link/p2572r0) at its [2022-06-08 telecon](https://github.com/sg16-unicode/sg16-meetings#june-8th-2022). The following poll was taken:

  - **Poll 1: Revise D2572R0 "std::format() fill character allowances" as discussed,
    and forward the paper so revised to LEWG as the recommended resolution of LWG3576
    and LWG3639.**
    - Attendance: 8 (2 abstention)

      | SF  | F   | N   | A   | SA  |
      | --: | --: | --: | --: | --: |
      |   3 |   3 |   0 |   0 |   0 |

    - Consensus in favor.

The changes in the published [P2572R0](https://wg21.link/p2572r0) revision reflect the SG16 requested changes.

Removing the SG16 label; this is ready for LWG pending approval of issue #1260 and (a revision of) [P2572](https://wg21.link/p2572) by LEWG.

**Comment by frederick-vs-ja** [comment]
This should have been fixed by cplusplus/draft#6144.
