### ISSUE TITLE
P0829 Freestanding Proposal

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/papers#113]
[P0829R4](https://wg21.link/p0829r4) Freestanding Proposal (Ben Craig)

**Comment by brycelelbach** [comment]
[Discussed at the Kona 2019 meeting by LEWGI](

__Champion:__ Ben Craig

__Minute Taker:__ Jeffrey Yasskin

__Start Overview:__ 13:24

__Start Review:__ 13:29

Formalizing `-fno-exceptions` would mean we wouldn’t have to cut out members.

Should new `std::` classes/class methods/functions be opt-in or opt-out?

__Start Polling:__ 14:01

We will poll some options and see what has the strongest consensus.

__POLL: Allow standard library classes (for example: `array`, `string_view`, `optional`, `bitset`, `variant`) to not have some members in freestanding mode (e.g. might not be declared in freestanding).__

|Strongly For|Weakly For|Neutral|Weakly Against|Strongly Against|
|-|-|-|-|-|
|5|3|4|3|0|

__Attendance:__ 17

That has weak consensus.

__POLL: Allow standard library classes (for example: `array`, `string_view`, `optional`, `bitset`, `variant`) to have some methods that have implementation-defined behavior in freestanding.__

|Strongly For|Weakly For|Neutral|Weakly Against|Strongly Against|
|-|-|-|-|-|
|1|4|5|4|1|

__Attendance:__ 17

That's not consensus.

Steve (A): Don’t want changes in behavior going between hosted vs freestanding.

Rene (A): Don’t like implementation-defined behavior.

__POLL: Library functions may `terminate` instead of throwing in freestanding.__

|Strongly For|Weakly For|Neutral|Weakly Against|Strongly Against|
|-|-|-|-|-|
|0|7|9|0|0|

__Attendance:__ 17

That has consensus.

__POLL: Allow standard library classes (for example: `array`, `string_view`, `optional`, `bitset`, `variant`) to have some members declared but not defined in freestanding.__

|Strongly For|Weakly For|Neutral|Weakly Against|Strongly Against|
|-|-|-|-|-|
|3|8|4|0|0|

__Attendance:__ 18

That has the strongest consensus of all the options we've polled.

__End:__ 14:15

__CONSENSUS: Bring a revision of P0829R4, with the guidance below, to LEWG(I) for further design review.__
   * __Explore allowing standard library classes to have some members declared but not defined in freestanding.__

**Comment by brycelelbach** [comment]
This should just go to LEWG when revised.

**Comment by ben-craig** [comment]
This specific paper number is dead.  Parts of the paper are going into other papers, with P1642 and P2198 being the pieces that are currently outstanding.  Closing.
