### ISSUE TITLE
CWG2538 Can standard attributes be syntactically ignored?

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/papers#1252]
See https://cplusplus.github.io/CWG/issues/2538.html

EWG discussed this in the context of P1774.
See also http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p2552r0.pdf #1212

**Comment by erichkeane** [comment]
During discussions in the  [May 26, 2022](https://wiki.edg.com/bin/view/Wg21telecons2022/EWG-2022-05-26) EWG meeting, we took the following polls related to CWG2538:

It is EWG's intent that [dcl.attr]/6 permits an implementation to completely ignore a standard attribute.
| SF | F | N | A | SA |
|----|---|---|---|----|
|  3 | 4 | 0 | 1 |  4 |

Result: Not Consensus

It is EWG's intent that [dcl.attr]/6 ONLY permits an implementation to ignore a standard attribute's effect, but not appertainment and argument parsing. See: CWG2538
| SF | F | N | A | SA |
|----|---|---|---|----|
|  2 | 6 | 3 | 0 |  2 |

Result: Consensus

The latter needs to be confirmed in Electronic Polling.

**Comment by jfbastien** [comment]
This was voted on in the June 2022 EWG polls. [Results are here](https://isocpp.org/files/papers/P1018R17.html#polls).

<ul style="margin-left: 0px; padding-left: 2em; color: rgb(221, 221, 221); font-family: sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(0, 0, 0); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li data-md="" style="margin: 0.25em 0px 0.5em; padding: 0px; position: relative;"><p style="margin: 0px;"><strong>🗳 Poll:</strong><span> </span>Resolve CWG2538 by clarifying that it is EWG’s intent that [<strong>dcl.attr</strong>]/6 ONLY permits an implementation to ignore a standard attribute’s effect, but not appertainment and argument parsing.</p></li></ul><p style="margin: 1em 0px; color: rgb(221, 221, 221); font-family: sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(0, 0, 0); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong>Poll votes:</strong></p>

SF | F | N | A | SA
-- | -- | -- | -- | --
11 | 6 | 4 | 0 | 3
Abstain: 4

<br style="color: rgb(221, 221, 221); font-family: sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(0, 0, 0); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong style="color: rgb(221, 221, 221); font-family: sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(0, 0, 0); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Poll outcome:</strong><span style="color: rgb(221, 221, 221); font-family: sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(0, 0, 0); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"><span> </span>❌ no consensus</span>
Note: There is sufficient implementor pushback, some implementors also voting neutral, to override the otherwise positive support.

**Comment by jfbastien** [comment]
Discussed in Kona 2022: https://github.com/cplusplus/nbballot/issues/430
