### ISSUE TITLE
P2596 Improve std::hive::reshape

### ISSUE THREAD

**Issue by brycelelbach** [cplusplus/papers#1256]
[P2596R0](https://wg21.link/P2596R0) Improve std::hive::reshape (Arthur O'Dwyer)

**Comment by ben-craig** [comment]
This was discussed in conjunction with P0447.  Here's the comment: https://github.com/cplusplus/papers/issues/328#issuecomment-1423397566

The author has 1 meeting to provide further rebuttals.

**Comment by brycelelbach** [comment]
Related to P0447 (#328)

**Comment by inbal2l** [comment]
The paper was discussed in 2023-02-07 Issaquah Library Evolution Meeting ([Full Minutes](http://wiki.edg.com/bin/view/Wg21issaquah2023/P0447#Library-Evolution-2023-02-07-15:30-17:30)), no consensus for the change proposed. 
There was no new revision since, will be reopened if a new revision comes up.
