### ISSUE TITLE
LWG3944 Formatters converting sequences of char to sequences of wchar_t

### ISSUE THREAD

**Issue by jwakely** [cplusplus/papers#1577]
https://cplusplus.github.io/LWG/issue3944

LWG would like SG16 to take a look at this new issue.

**Comment by tahonermann** [comment]
> LWG would like SG16 to take a look at this new issue.

And so we shall.

**Comment by tahonermann** [comment]
SG16 reviewed this issue during its [2023-07-12](https://github.com/sg16-unicode/sg16-meetings#july-12th-2023) and [2023-07-26](https://github.com/sg16-unicode/sg16-meetings#july-26th-2023) meetings. The following poll was taken:

- **Poll 3: Recommend the proposed resolution to LWG3944 "Formatters converting sequences of char to sequences of wchar_t" to LWG, after fixing the typo.**
  - Attendees: 12
  - No objection to unanimous consent.

The typo referenced in the poll concerned a markup issue that was observed; the extent of the struck text did not include a trailing `>` character that it should have. The proposed resolution has already been updated to address this.

This issue is now ready for LWG; I'm removing the SG16 label.

**Comment by JeffGarland** [comment]
This was moved to Ready in Tokyo

**Comment by JeffGarland** [comment]
The issue was part of the completed issues for St. Louis and is now in status Working Paper.  Closing this issue.

[St. Louis 2024-06-29; Status changed: Voting → WP.]
