### ISSUE TITLE
P1351 Intrusive smart pointer feedback

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/papers#163]
[P1351R0](https://wg21.link/p1351r0) Intrusive smart pointer feedback (Mark Zeren)

**Comment by brycelelbach** [comment]
[Kona 2019-02 LEWGI Minutes](http://wiki.edg.com/bin/view/Wg21kona2019/P1351)

[P1351R0](https://wg21.link/P1351R0) Intrusive Smart Pointer Feedback

__Champion:__ Georgi Dimitrov

__Minute Taker:__ Nathan Meyers

__Start Overview:__ 10:20

__Start Discussion:__ 10:30

__Start Polling:__ 10:53

__POLL: `std::retain_ptr` and `std::out_ptr` should have an `operator=(T__)`__

|Strongly For|Weakly For|Neutral|Weakly Against|Strongly Against|
|-|-|-|-|-|
|1|1|1|1|3|

__Attendance:__ 11

That has no consensus.

__POLL: `std::retain_ptr` and `std::out_ptr` should allow customization of the default adopt/retain semantics (e.g. the behavior of the constructor/`reset()` that doesn’t take a tag).__

|Strongly For|Weakly For|Neutral|Weakly Against|Strongly Against|
|-|-|-|-|-|
|1|0|1|4|2|

__Attendance:__ 11

That has no consensus.

ThePHD (SF): Like having the ability to customize the behavior; it means we don’t have to pick one default.

__POLL: `std::retain_ptr` should retain by default (e.g. the behavior of the constructor/`reset()` that doesn’t take a tag) instead of adopting.__

|Strongly For|Weakly For|Neutral|Weakly Against|Strongly Against|
|-|-|-|-|-|
|2|3|2|0|1|

__Attendance:__ 11

That has consensus.

__POLL: `std::retain_ptr` should have a from-pointer constructor/`reset()` that does not take an adopt/retain tag (e.g. has a default).`

|Strongly For|Weakly For|Neutral|Weakly Against|Strongly Against|
|-|-|-|-|-|
|1|2|1|2|1|

__Attendance:__ 11

No consensus either way; we leave it up to the authors.

__End:__ 11:08

**Comment by cor3ntin** [comment]
I'm closing this because https://github.com/cplusplus/papers/issues/324 was abandoned by the author.
