### ISSUE TITLE
LWG 4064: Clarify that std::launder is not needed when using the result of std::memcpy

### ISSUE THREAD

**Issue by jwakely** [cplusplus/papers#1983]
Could CWG please take a look at this proposed resolution and confirm that they're happy with it:
https://cplusplus.github.io/LWG/issue4064

**Comment by jensmaurer** [comment]
CWG 2024-06-25 in St. Louis: The proposed resolution is not correct, because there are situations in which memcpy works (because it is operating on a trivially copyable type), yet the type in question is not an implicitly lifetime type.  In that case, there is no "suitable created object".  (An example of such a type is one with a trivial destructor and a trivial copy assignment operator where all other special member functions are deleted.)

Suggested amendments to the proposed resolution, including a drive-by fix to make everything singular:

> The functions memcpy and memmove are signal-safe (17.13.5 [[support.signal]](https://wg21.link/support.signal)). <del>Both</del> <ins>Each of these</ins> functions implicitly <del>create</del> <ins>creates</ins> objects (6.7.2 [[intro.object]](https://wg21.link/intro.object)) in the destination region of storage immediately prior to copying the sequence of characters to the destination. <ins>Each of these functions returns a pointer to a suitable created object, if any, otherwise the value of the first parameter.</ins>

**Comment by jwakely** [comment]
LWG are happy with the CWG wording and moved it to Ready status. If CWG want to look at it again, please feel free to do so. We can reopen it if you want to change it, otherwise it will get polled in Wrocław.

**Comment by jensmaurer** [comment]
CWG 2024-11-18: Approved.
